apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: expense
spec:
  containers:
  - name: debug
    image: sathishreddy27/debug:v1.0
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
        
